<a href="https://colab.research.google.com/github/Lasal0425/Machine-Learning-Tutorials/blob/main/Tute9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

In [2]:
# To expand e scientific notation
pd.set_option('display.float_format', '{:.2f}'.format)
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Tutorial 09/house_prices.csv')
df.describe(include="all").transpose()

,count,mean,std,min,25%,50%,75%,max
id,21613.00,4580301520.86,2876565571.31,1000102.00,2123049194.00,3904930410.00,7308900445.00,9900000190.00
price,21613.00,540182.16,367362.23,75000.00,321950.00,450000.00,645000.00,7700000.00
bedrooms,21613.00,3.37,0.93,0.00,3.00,3.00,4.00,33.00
bathrooms,21613.00,2.11,0.77,0.00,1.75,2.25,2.50,8.00
sqft_living,21613.00,2079.90,918.44,290.00,1427.00,1910.00,2550.00,13540.00
sqft_lot,21613.00,15106.97,41420.51,520.00,5040.00,7618.00,10688.00,1651359.00
floors,21613.00,1.49,0.54,1.00,1.00,1.50,2.00,3.50
waterfront,21613.00,0.01,0.09,0.00,0.00,0.00,0.00,1.00
view,21613.00,0.23,0.77,0.00,0.00,0.00,0.00,4.00
condition,21613.00,3.41,0.65,1.00,3.00,3.00,4.00,5.00
grade,21613.00,7.66,1.18,1.00,7.00,7.00,8.00,13.00
sqft_above,21613.00,1788.39,828.09,290.00,1190.00,1560.00,2210.00,9410.00
sqft_basement,21613.00,291.51,442.58,0.00,0.00,0.00,560.00,4820.00
sqft_living15,21613.00,1986.55,685.39,399.00,1490.00,1840.00,2360.00,6210.00
sqft_lot15,21613.00,12768.46,27304.18,651.00,5100.00,7620.00,10083.00,871200.00

In [3]:
#Assign your input and output features
x = df.drop(['price', 'id'], axis=1)
y = df['price']

#Split your data into training and testing
trainX, testX, trainY, testY = train_test_split(x, y, test_size = 0.5)

# Scale your dataset with standard scaler
sc=StandardScaler()
scaler = sc.fit(trainX)
trainX_scaled = scaler.transform(trainX)
testX_scaled = scaler.transform(testX)

In [4]:
mlp_reg = MLPRegressor(hidden_layer_sizes=(150,100,50), max_iter = 300,activation = 'relu',  solver = 'adam')
mlp_reg.fit(trainX_scaled, trainY)

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPRegressor(hidden_layer_sizes=(150, 100, 50), max_iter=300)

In [5]:
y_pred = mlp_reg.predict(testX_scaled)
prediction_table = pd.DataFrame({'Actual': testY, 'Predicted': y_pred})
prediction_table.head(10)

       Actual  Predicted
4931   300000  498877.26
5111   492000  422593.59
20561  485230  624734.54
13151  394000  271501.27
14711  352500  515029.87
6317   733000  694630.30
17226  525000  379285.30
1312   537250  663269.89
8632   601150  479067.64
21249  494000  507955.01

In [6]:
print('Mean Absolute Error:', metrics.mean_absolute_error(testY, y_pred))
print('Mean Absolute Percentage Error MAPE:', metrics.mean_absolute_percentage_error(testY, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(testY, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(testY, y_pred)))
print('Mean R-Square:', metrics.r2_score(testY, y_pred))

Mean Absolute Error: 132622.57078113497
Mean Absolute Percentage Error MAPE: 0.27864402273779976
Mean Squared Error: 39953263362.36933
Root Mean Squared Error: 199883.12425607454
Mean R-Square: 0.6948006290552622